package com.techwave.taskapp.service.mapper;

import com.techwave.taskapp.dto.CreateTaskRequest;
import com.techwave.taskapp.entity.Task;
import com.techwave.taskapp.enums.TaskStatus;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.Instant;

/**
 * TaskMapper - Handles mapping between DTOs and Entities.
 * 
 * SOLID Principles:
 * - Single Responsibility Principle (SRP): Only responsible for data mapping
 * - Open/Closed Principle (OCP): Easy to extend with new mapping methods
 * 
 * Separation of Concerns:
 * - Isolates mapping logic from business logic
 * - Makes mapping logic reusable and testable
 * - Centralizes DTO-Entity conversion rules
 */
@Slf4j
@Component
public class TaskMapper {
    
    /**
     * Map CreateTaskRequest to Task entity for persistence.
     * 
     * Mapping Rules:
     * - ID: Will be generated by repository (set to null)
     * - Title: Direct mapping (should be sanitized by validator)
     * - Description: Direct mapping (null if not provided)
     * - Status: Defaults to PENDING per business rules
     * - CreatedAt: Set to current UTC timestamp
     * 
     * @param request Sanitized CreateTaskRequest
     * @return Task entity ready for persistence
     */
    public Task mapToEntity(CreateTaskRequest request) {
        log.debug("Mapping CreateTaskRequest to Task entity");
        
        Task task = new Task();
        task.setId(null);  // Will be generated by repository
        task.setTitle(request.getTitle());
        task.setDescription(request.getDescription());
        task.setStatus(TaskStatus.PENDING);  // Default status per FRD
        task.setCreatedAt(Instant.now());    // Current UTC timestamp
        
        log.debug("Task entity mapped - title: '{}', status: {}, description provided: {}", 
                  task.getTitle(), 
                  task.getStatus(), 
                  task.getDescription() != null);
        
        return task;
    }
    
    /**
     * Create a new Task entity with custom status (for future use).
     * 
     * @param request Sanitized CreateTaskRequest
     * @param status Custom task status
     * @return Task entity with specified status
     */
    public Task mapToEntityWithStatus(CreateTaskRequest request, TaskStatus status) {
        log.debug("Mapping CreateTaskRequest to Task entity with status: {}", status);
        
        Task task = mapToEntity(request);
        task.setStatus(status);
        
        log.debug("Task entity mapped with custom status: {}", status);
        
        return task;
    }
}